base:
  font: ./fonts/SourceHanSansCN-Light.otf
  bold_font: ./fonts/SourceHanSansCN-Bold.otf
  #input_dir: ./input
  #output_dir: ./output
  input_dir: "C:/Users/XU/OneDrive2 - mail.sdu.edu.cn/OneDrive - mail.sdu.edu.cn/LightroomOutput/JPEG"
  output_dir: "C:/Users/XU/OneDrive2 - mail.sdu.edu.cn/OneDrive - mail.sdu.edu.cn/LightroomOutput/JPEGwithWaterMark"
  quality: 90

logo: # true or false
  enable: true
  makes:
    nikon:
      id: NIKON
      path: ./logos/nikon.png
    canon:
      id: Canon
      path: ./logos/canon_04.13.2421.png
    sony:
      id: SONY
      path: ./logos/sony.png
    pentax:
      id: PENTAX
      path: ./logos/pentax.png
    panasonic:
      id: Panasonic
      path: ./logos/panasonic.png
    olympus:
      id: Olympus
      path: ./logos/olympus_blue_gold.png
    fujifilm:
      id: FUJIFILM
      path: ./logos/fujifilm.png
    leica:
      id: leica
      path: ./logos/leica_logo.png
    rioch:
      id: RIOCH
      path: ./logos/ricoh.png
    hasselblad:
      id: HASSELBLAD
      path: ./logos/hasselblad.png

layout: # you can select one type in ['normal'], may more type supports later
  # you can get more information in https://lsvm.xyz/2023/02/semi-utils-intro/
  type: normal
  elements: # the information displayed in the watermark
    # you can select from ['Date', 'Model', 'LensModel', 'Param', 'Make', 'None']
    - id: LensModel
    - id: Model
    - id: Param
    - id: Date
