base:
  alternative_bold_font: ./fonts/Roboto-Medium.ttf
  alternative_font: ./fonts/Roboto-Regular.ttf
  bold_font: ./fonts/AlibabaPuHuiTi-2-85-Bold.otf
  bold_font_size: 1
  font: ./fonts/AlibabaPuHuiTi-2-45-Light.otf
  font_size: 1
  input_dir: ./input
  output_dir: ./output
  quality: 100
global:
  focal_length:
    use_equivalent_focal_length: false
  padding_with_original_ratio:
    enable: false
  shadow:
    enable: false
  white_margin:
    enable: true
    width: 3
layout:
  background_color: '#ffffff'
  elements:
    left_bottom:
      color: '#757575'
      is_bold: false
      name: Model
    left_top:
      color: '#212121'
      is_bold: true
      name: LensModel
    right_bottom:
      color: '#757575'
      is_bold: false
      name: Datetime
      value: Photo by NONE
    right_top:
      color: '#212121'
      is_bold: true
      name: Param
  logo_enable: false
  logo_position: left
  type: watermark_right_logo
logo:
  makes:
    apple:
      id: APPLE
      path: ./logos/apple.png
    canon:
      id: Canon
      path: ./logos/canon.png
    default:
      id: ''
      path: ''
    dji:
      id: DJI
      path: ./logos/DJI.jpg
    fujifilm:
      id: FUJIFILM
      path: ./logos/fujifilm.png
    hasselblad:
      id: HASSELBLAD
      path: ./logos/hasselblad.png
    huawei:
      id: HUAWEI
      path: ./logos/xmage.jpg
    leica:
      id: leica
      path: ./logos/leica_logo.png
    nikon:
      id: NIKON
      path: ./logos/nikon.png
    olympus:
      id: Olympus
      path: ./logos/olympus_blue_gold.png
    panasonic:
      id: Panasonic
      path: ./logos/panasonic.png
    pentax:
      id: PENTAX
      path: ./logos/pentax.png
    ricoh:
      id: RICOH
      path: ./logos/ricoh.png
    sony:
      id: SONY
      path: ./logos/sony.png
